### ISSUE TITLE
带有空格的Python解释器路径

### ISSUE THREAD

**Issue by imagebuilder1837** [gaogaotiantian/viztracer-vscode#1]
右键"Trace with VizTracer"
![20231216202731890.png](https://raw.githubusercontent.com/image-builder-1837/ImageHost/main/20231216202731890.png)

**Comment by gaogaotiantian** [comment]
在 https://github.com/gaogaotiantian/viztracer-vscode/commit/da8bf65060972a7e0afe13b5c8d3420bb966625b 中修复了
