### ISSUE TITLE
View result web is blank page

### ISSUE THREAD

**Issue by BackMountainDevil** [gaogaotiantian/viztracer-vscode#2]
result.json file is large(485.71 MB). View with viztracer(v0.2.2) got a total white page in vscode.

```bash
$ python -m viztracer  -- entry.py
.....
nnection.py", line 383, in _recv
    raise EOFError
EOFError
Wait for child processes to finish, Ctrl+C to skip                              
Dumping trace data, total entries: 3000008                                      
Total Entries: 3000008                                                          

Circular buffer is full, you lost some early data, but you still have the most recent data.
    If you need more buffer, use "viztracer --tracer_entries <entry_number>"
    Or, you can try the filter options to filter out some data you don't need
    use --quiet to shut me up

Use the following command to open the report:
vizviewer /home/yicairun/repo/rl/sadma_github/envs/mapf_env/result.json
[W CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
```

**Comment by gaogaotiantian** [comment]
You posted a trace log so I'm not sure if it's related.

When you say "white page", how long did you wait? It could take a relatively long time for Perfetto to load it. What's a blank look like? Could you share a screenshot?

**Comment by BackMountainDevil** [comment]
work in firefox and vscode.. try more times. sorry to ask a easy qa. I guess it is just fetching js or css files

**Comment by BackMountainDevil** [comment]
In case we want to know what it looks like. I paste a img happened just now. Left side is firefox while the right side is vscode.

![截图_2023-12-27_10-01-41](https://github.com/gaogaotiantian/viztracer-vscode/assets/59185302/7c802256-611d-4f1c-977c-35f99e6ca61b)
